---
- name: add virtaulbox repo key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present
- name: add virtaulbox repo
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' state=present
- name: install virtualbox
  apt: name='virtualbox-4.3' state=latest

