---
- name: install common packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - curl 
    - htop
    - ack-grep
    - sysstat 
    - tree 
    - iotop 
    - ifstat 
    - colordiff
    - build-essential

- name: create dev user
  user: name=dev uid={{ dev_user_id }}
