---
- hosts: 'local' 
  vars:
  - ansible_sudo_pass: changeme
  roles: 
    - jareks.devstrap.common
    - jareks.devstrap.bash
    - jareks.devstrap.git
    - jareks.devstrap.vim
    - jareks.devstrap.inputrc
